name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20-alpine3.17

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
        env:
          SESSION_SECRET: f4z4gs$Gcg
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
          NODE_ENV: test
